# Generated by Django 4.1.2 on 2022-10-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
