# Generated by Django 4.1 on 2022-10-22 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_remove_user_profile_pic_alter_tech_history_how_long_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_mentor",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="user",
            field=models.OneToOneField(
                default="default.jpg",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tech_history",
            name="how_long",
            field=models.CharField(
                choices=[
                    ("3-5", "Between 3-5 years"),
                    ("1", "Less than one year"),
                    ("1-3", "Between 1-3 years"),
                    ("5+", "5 years+"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Female", "Female"), ("Male", "Male")], max_length=50
            ),
        ),
    ]
