# Generated by Django 4.1 on 2022-10-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_is_mentor_alter_image_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tech_history",
            name="how_long",
            field=models.CharField(
                choices=[
                    ("1", "Less than one year"),
                    ("1-3", "Between 1-3 years"),
                    ("3-5", "Between 3-5 years"),
                    ("5+", "5 years+"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=50
            ),
        ),
    ]
