# Generated by Django 4.1.2 on 2022-10-22 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
        ("accounts", "0007_usercourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="learn.course"
            ),
        ),
        migrations.AddField(
            model_name="usercourse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usercourse",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
