# Generated by Django 4.1.2 on 2022-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="regraded",
        ),
        migrations.AddField(
            model_name="grade",
            name="regraded",
            field=models.BooleanField(default=False),
        ),
    ]
