# Generated by Django 4.1.2 on 2022-10-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0002_remove_task_regraded_grade_regraded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="object_id",
        ),
        migrations.AddField(
            model_name="grade",
            name="answer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="learn.answertask",
            ),
            preserve_default=False,
        ),
    ]
