# Generated by Django 4.1.2 on 2022-10-30 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0002_alter_answertask_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercourse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
