# Generated by Django 4.1.2 on 2022-10-26 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_alter_grade_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learn.answertask'),
        ),
    ]
