# Generated by Django 4.1.2 on 2022-10-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_alter_grade_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='learn.task'),
        ),
    ]
